// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD3cK31L2M1EQYEAiRhZwv35CcF_LExb10',
    appId: '1:214167132788:web:521f4923ad88664830cf21',
    messagingSenderId: '214167132788',
    projectId: 'mission-good-food',
    authDomain: 'mission-good-food.firebaseapp.com',
    storageBucket: 'mission-good-food.firebasestorage.app',
    measurementId: 'G-FP68H024QC',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCmyPBaYAtY26Gbo9tkPxBgEHjBZZDNMu8',
    appId: '1:214167132788:android:f31a7da02406d67430cf21',
    messagingSenderId: '214167132788',
    projectId: 'mission-good-food',
    storageBucket: 'mission-good-food.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC_Urt4BpOYiHnZOUeM9zHpf6pTDVBKDMA',
    appId: '1:214167132788:ios:069a30f002552cce30cf21',
    messagingSenderId: '214167132788',
    projectId: 'mission-good-food',
    storageBucket: 'mission-good-food.firebasestorage.app',
    iosClientId: '214167132788-ngkbuf2nscogvdtnmarltshc15eks2bd.apps.googleusercontent.com',
    iosBundleId: 'com.example.goodFoodApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC_Urt4BpOYiHnZOUeM9zHpf6pTDVBKDMA',
    appId: '1:214167132788:ios:069a30f002552cce30cf21',
    messagingSenderId: '214167132788',
    projectId: 'mission-good-food',
    storageBucket: 'mission-good-food.firebasestorage.app',
    iosClientId: '214167132788-ngkbuf2nscogvdtnmarltshc15eks2bd.apps.googleusercontent.com',
    iosBundleId: 'com.example.goodFoodApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD3cK31L2M1EQYEAiRhZwv35CcF_LExb10',
    appId: '1:214167132788:web:fc0e1cd51ad8c9c730cf21',
    messagingSenderId: '214167132788',
    projectId: 'mission-good-food',
    authDomain: 'mission-good-food.firebaseapp.com',
    storageBucket: 'mission-good-food.firebasestorage.app',
    measurementId: 'G-3DP8KEL3DK',
  );

}